uitest login Adopter
CarolinaMora/PetTracker pull request #182
Opened 2021-06-29 17:54 UTC by neorb

#169 Purebas UI -Login adopter
Se realizo la Uitest para Login adopter. Se realizao algunos cambios como: Cambios en los nombres de editext adopter para que se ajuste mas a la descripcion

2021-06-29 22:52 UTC, CarolinaMora requested changes
Todos los cambios en los xml deben ser revertidos, si se quiere colocar un mejor nombre a estos elementos se puede hacer como mejora, el objetivo de este issue es otro

2021-06-30 04:59 UTC, neorb commented
Se regreso las xml a su estado anterior. Todos los campos vuelven a su estado anterior

2021-06-30 16:00 UTC, CarolinaMora requested changes

2021-06-30 16:00 UTC, CarolinaMora commented on app/src/main/java/com/teammovil/pettracker/ui/adopterlogin/AdopterLoginFragment.kt
> -                FieldView(passAdopted.text.toString())
Esta línea no debió de ser borrada y cambiada por la otra ya que ahora está repetida y seguramente el  login no funciona

2021-06-30 17:31 UTC, neorb commented on app/src/main/java/com/teammovil/pettracker/ui/adopterlogin/AdopterLoginFragment.kt
> -                FieldView(passAdopted.text.toString())
Se corrige el cambio solicitado. fue agregado "FieldView(passAdopted.text.toString())".

2021-06-30 23:35 UTC, CarolinaMora requested changes
Corregir o elimnar la última prueba

2021-06-30 23:35 UTC, CarolinaMora commented on app/src/androidTest/java/com/teammovil/pettracker/ui/LoginAdopterUITest.kt
> +    fun clickAdopterRegisterButton() {
En esta prueba no hay ningún check, que se está probando?

2021-07-01 04:14 UTC, neorb commented on app/src/androidTest/java/com/teammovil/pettracker/ui/LoginAdopterUITest.kt
> +    fun clickAdopterRegisterButton() {
Se agrego un Check al Test clickAdopterRegisterButton" que comprueba el nombre de la "action bar"

2021-07-01 15:01 UTC, CarolinaMora approved these changes

2021-07-01 15:01 UTC, merged