Feature/159 integrationtest pet detail
CarolinaMora/PetTracker pull request #185
Opened 2021-06-29 22:19 UTC by neicaro

close #159

2021-06-29 23:21 UTC, Razorkrawzer requested changes
Hay conflictos para hacer el merge a develop. Me apoyas corrigiendolos.

2021-07-01 20:12 UTC, neicaro commented
resolvi conflictos en FakeData

2021-07-01 23:32 UTC, Razorkrawzer approved these changes

2021-07-01 23:34 UTC, Razorkrawzer commented
closed(#159)

2021-07-01 23:35 UTC, merged