Fix/82 rescuer login validations
CarolinaMora/PetTracker pull request #94
Opened 2021-05-29 17:30 UTC by neorb

#82 closed

2021-05-29 18:28 UTC, neicaro commented on .idea/compiler.xml
> -      <module name="Pet_Tracker.app" target="1.8" />
los archivos que estan dentro de .idea no deben de subirse, favor de regresar al cambio anterior

2021-05-29 18:45 UTC, neicaro commented on domain/src/main/java/com/teammovil/domain/UserRescuer.kt
> +package com.teammovil.domain
No se debe de crear esta clase, porque no es un objecto de dominio

2021-05-29 18:45 UTC, neicaro commented on domain/src/main/java/com/teammovil/domain/UserRescuer.kt
> +package com.teammovil.domain
Manejar los campos directamente como strings

2021-05-29 18:49 UTC, neicaro requested changes
favor de  actualizar los errores comentados en la junta :)

2021-05-30 16:23 UTC, neorb commented on domain/src/main/java/com/teammovil/domain/UserRescuer.kt
> +package com.teammovil.domain
El objeto que fue creado ya fue borrado y se manejaron los campos como Strings

2021-05-30 18:07 UTC, neicaro approved these changes
Revisado

2021-05-30 18:09 UTC, merged